//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberBoss.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than or equal to zero.
        /// </summary>
        public static string AMOUNT_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barber name must be at least 2 characters.
        /// </summary>
        public static string BARBER_NAME_MUST_BE_GREATHER_THAN_TWO_LETTERS {
            get {
                return ResourceManager.GetString("BARBER_NAME_MUST_BE_GREATHER_THAN_TWO_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barber name must be less than 80 characters.
        /// </summary>
        public static string BARBER_NAME_MUST_BE_LESS_THAN_EIGHTY_LETTERS {
            get {
                return ResourceManager.GetString("BARBER_NAME_MUST_BE_LESS_THAN_EIGHTY_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Not Found.
        /// </summary>
        public static string BILLING_NOT_FOUND {
            get {
                return ResourceManager.GetString("BILLING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name must be at least 2 characters.
        /// </summary>
        public static string CLIENT_NAME_MUST_BE_GREATHER_THAN_TWO_LETTERS {
            get {
                return ResourceManager.GetString("CLIENT_NAME_MUST_BE_GREATHER_THAN_TWO_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name must be less than 120 characters.
        /// </summary>
        public static string CLIENT_NAME_MUST_BE_LESS_THAN_ONE_HUNDRED_TWENTY_LETTERS {
            get {
                return ResourceManager.GetString("CLIENT_NAME_MUST_BE_LESS_THAN_ONE_HUNDRED_TWENTY_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date cannot be in the future.
        /// </summary>
        public static string CREATED_AT_CANNOT_BE_FUTURE {
            get {
                return ResourceManager.GetString("CREATED_AT_CANNOT_BE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date cannot be in the future.
        /// </summary>
        public static string DATE_CANNOT_BE_FUTURE {
            get {
                return ResourceManager.GetString("DATE_CANNOT_BE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payment method.
        /// </summary>
        public static string PAYMENT_METHOD_INVALID {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name must be at least 2 characters.
        /// </summary>
        public static string SERVICE_NAME_MUST_BE_GREATHER_THAN_TWO_LETTERS {
            get {
                return ResourceManager.GetString("SERVICE_NAME_MUST_BE_GREATHER_THAN_TWO_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name must be less than 120 characters.
        /// </summary>
        public static string SERVICE_NAME_MUST_BE_LESS_THAN_ONE_HUNDRED_TWENTY_LETTERS {
            get {
                return ResourceManager.GetString("SERVICE_NAME_MUST_BE_LESS_THAN_ONE_HUNDRED_TWENTY_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status.
        /// </summary>
        public static string STATUS_INVALID {
            get {
                return ResourceManager.GetString("STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated date cannot be in the future.
        /// </summary>
        public static string UPDATED_AT_CANNOT_BE_FUTURE {
            get {
                return ResourceManager.GetString("UPDATED_AT_CANNOT_BE_FUTURE", resourceCulture);
            }
        }
    }
}
